openapi: 3.0.0
info:
 title: DietiEstates25
 version: 1.0.0
paths:
  /api/auth/login:
    $ref: './paths/login.yaml'
  /api/customers:
    $ref: './paths/customers.yaml'
  /api/customers/{customer-id}:
    $ref: './paths/customer-id.yaml'
  /api/agencies:
    $ref: './paths/agencies/agencies.yaml'
  /api/agencies/{agency-id}/managers:
    $ref: './paths/agencies/managers.yaml'
  /api/agencies/{agency-id}/managers/{manager-id}:
    $ref: './paths/agencies/manager-id.yaml'
  /api/agencies/{agency-id}/agents/:
    $ref: './paths/agencies/agents.yaml'
  /api/agencies/{agency-id}/agents/{agent-id}:
    $ref: './paths/agencies/agent-id.yaml'
  /api/listings/houses:
    $ref: './paths/listings/houses.yaml'
  /api/listings/buildings:
    $ref: './paths/listings/buildings.yaml'
  /api/listings/garages:
    $ref: './paths/listings/garages.yaml'
  /api/listings/lands:
    $ref: './paths/listings/lands.yaml'
  /api/listings/{listing-type}/{listing-id}:
    $ref: './paths/listings/listing-id.yaml'
  /api/listings/houses/{listing-id}:
    $ref: './paths/listings/house-listing-id.yaml'
  /api/listings/garages/{listing-id}:
    $ref: './paths/listings/garage-listing-id.yaml'
  /api/listings/buildings/{listing-id}:
    $ref: './paths/listings/building-listing-id.yaml'
  /api/listings/lands/{listing-id}:
    $ref: './paths/listings/land-listing-id.yaml'
  /api/recent-searches/{user-id}:
    $ref: './paths/recent-searches.yaml'
  /api/agent-review:
    $ref: './paths/agent-review.yaml'
  /api/agent-review/{agent-id}:
    $ref: './paths/agent-review-agent-id.yaml'
  /api/notifications:
    $ref: './paths/notifications.yaml'
  /api/notifications/settings:
    $ref: './paths/notification-settings.yaml'
  /api/starred-listings:
    $ref: './paths/starred-listings.yaml'
  /api/visits:
    $ref: './paths/visits/visits.yaml'
  /api/visit-requests:
    $ref: './paths/visits/visit-requests.yaml'
  /api/visit-requests/{visit-request-id}/accept:
    $ref: './paths/visits/visit-requests-id-accept.yaml'
  /api/visit-requests/{visit-request-id}/reject:
    $ref: './paths/visits/visit-requests-id-reject.yaml'
  /api/images/listings/{listing-id}:
    $ref: './paths/images-listings.yaml'
  /api/images/users/{user-id}:
    $ref: './paths/images-users.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT