steps:
  # Build the application
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/dietiestates25-451613/dietiestates-repo/dietiestates25', '.']

  # Push the Docker image
  - name: 'docker'
    args: ['push', 'europe-west8-docker.pkg.dev/dietiestates25-451613/dietiestates-repo/dietiestates25']

images:
  - 'europe-west8-docker.pkg.dev/dietiestates25-451613/dietiestates-repo/dietiestates25'
