services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build: .
    container_name: dietiestates25
    restart: always
    depends_on:
      - postgis
    environment:
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET} 
      JWT_EXPIRING_TIME_IN_MINUTES: 60
      GC_PROJECT_ID: ${GC_PROJECT_ID}
      GC_BUCKET_NAME: ${GC_BUCKET_NAME}
    ports:
      - "8080:8080"
    networks:
      - my_network

  test:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies between runs
    depends_on:
      - postgis
    environment:
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRING_TIME_IN_MINUTES: 60
      GC_PROJECT_ID: ${GC_PROJECT_ID}
      GC_BUCKET_NAME: ${GC_BUCKET_NAME}
      SPRING_PROFILES_ACTIVE: test
    command: mvn test
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
