put:
  tags:
    - Notification Settings
  operationId: update-notification-settings
  description: A user can only modify its own settings
  security:
    - BearerAuth: []
  parameters:
    - name: 
      in: userId
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../components/dtos.yaml#/NotificationSettingsDto'
    required: true
  responses:
    '204':
      description: Ok
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../components/dtos.yaml#/ErrorDetails'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '../components/dtos.yaml#/ErrorDetails'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '../components/dtos.yaml#/ErrorDetails'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '../components/dtos.yaml#/ErrorDetails'